version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: uncoverj_db
    restart: always
    environment:
      POSTGRES_USER: uncoverj_user
      POSTGRES_PASSWORD: uncoverj_password
      POSTGRES_DB: uncoverj_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: uncoverj_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
